# Generated by Django 3.0.14 on 2024-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sobreNome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=12)),
                ('rg', models.CharField(max_length=12)),
                ('ctps', models.CharField(max_length=15)),
                ('pis', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
    ]
